package sine;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import sine.command.Command;
import sine.exception.SineException;
import sine.parser.Parser;
import sine.storage.Storage;
import sine.task.TaskList;
import sine.ui.Ui;

/**
 * Starts the Sine chatbot application.
 */
public class Sine {
    private final Ui ui;
    private final Storage storage;
    private final Parser parser;
    private TaskList tasks;
    private boolean isInitialized;

    /**
     * Creates a chatbot that stores its tasks at the given relative file path.
     *
     * @param filePath Relative path to the task data file.
     */
    public Sine(String filePath) {
        this.ui = new Ui();
        this.storage = new Storage(filePath);
        this.parser = new Parser();
        this.tasks = new TaskList();
        this.isInitialized = false;
    }

    /**
     * Loads saved tasks and processes commands until input ends or the user exits.
     */
    public void run() {
        ui.showWelcome();
        initializeTasks(ui);
        while (ui.hasNextCommand()) {
            String command = ui.readCommand();
            boolean isExit = executeCommand(command, ui);
            if (isExit) {
                break;
            }
        }
    }

    /**
     * Processes one command and returns the chatbot response for a graphical UI.
     *
     * @param input Command entered by the user.
     * @return Response generated by the chatbot.
     */
    public String getResponse(String input) {
        ByteArrayOutputStream responseBuffer = new ByteArrayOutputStream();
        try (PrintStream responseOutput = new PrintStream(
                responseBuffer, true, StandardCharsets.UTF_8)) {
            Ui responseUi = new Ui(responseOutput);
            initializeTasks(responseUi);
            executeCommand(input, responseUi);
        }
        return responseBuffer.toString(StandardCharsets.UTF_8).strip();
    }

    /**
     * Loads tasks once, falling back to an empty list if saved data cannot be read.
     */
    private void initializeTasks(Ui activeUi) {
        if (isInitialized) {
            return;
        }

        try {
            tasks = new TaskList(storage.load());
        } catch (IOException exception) {
            tasks = new TaskList();
            activeUi.showLoadingError();
        }
        isInitialized = true;
    }

    /**
     * Executes a command against initialized tasks and reports recoverable errors to the calling UI.
     */
    private boolean executeCommand(String input, Ui activeUi) {
        // Both console and GUI entry points must load saved tasks before processing commands.
        assert isInitialized : "Tasks must be initialized before executing a command";
        // Successful loading and loading-error recovery must both leave a usable task list.
        assert tasks != null : "Initialized tasks must not be null";
        // Internal callers must provide the UI that receives this command's response.
        assert activeUi != null : "Command execution requires a response UI";

        try {
            Command parsedCommand = parser.parse(input, tasks.size());
            // Parsing must either produce a command or throw a recoverable SineException.
            assert parsedCommand != null : "Successful parsing must return a command";
            parsedCommand.execute(tasks, activeUi, storage);
            return parsedCommand.isExit();
        } catch (SineException exception) {
            activeUi.showCommandError(exception.getMessage());
        } catch (IOException exception) {
            activeUi.showSavingError();
        }
        return false;
    }

    /**
     * Starts Sine using the default relative data-file path.
     *
     * @param args Command-line arguments, which Sine does not use.
     */
    public static void main(String[] args) {
        new Sine("data/sine.txt").run();
    }
}
